[package]
name = "lihkg"
version = "0.1.0"
edition = "2021"

[dependencies]
xz2 = "0.1.7"
tar = "0.4.40"
serde = "1.0"
serde_json = "1.0"
scraper = "0.18.1"
regex = "1"
html5ever = "0.26"
lazy_static = "1.4.0"
